name: Esegui script Python

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */2 * * *"  # Esegue lo script ogni 2 ore

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v3

      - name: Imposta Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installa le dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Esegui lo script
        run: python run.py
